name: Publish Docker image

on:
  push:
    branches: ["master"]

jobs:
  tests:
    name: Run unit tests
    uses: ./.github/workflows/tests.yml

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
      
    - name: Log in to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Docker Build
      run: |
        docker build . --file Dockerfile --tag python-pipeline:latest
    - name: Docker Push
      run: |
        docker tag python-pipeline:latest ${{secrets.DOCKER_USER}}/python-pipeline:latest
        docker push ${{ secrets.DOCKER_USER }}/python-pipeline:latest
